### ISSUE TITLE
Your data folder should not be on Github

### ISSUE THREAD

**Issue by xanoni** [soulmachine/GasPrice#1]
It is huge. I just want the script ;-)

**Comment by soulmachine** [comment]
I will rebase this repo from time time, to make it easier to git clone.

The purpose of this repo is to publish data, so  the `data` folder is necessary.

**Comment by xanoni** [comment]
> I will rebase this repo from time time, to make it easier to git clone.
> 
> The purpose of this repo is to publish data, so the `data` folder is necessary.

Okay. Thought this was about the script :)
